///////////////////////////////////////////////////////////
//  Organization.cs
//  Implementation of the Class Organization
//  Generated by Enterprise Architect
//  Created on:      15-May-2013 9:40:05 PM
//  Original author: Vladimir
///////////////////////////////////////////////////////////

namespace WoaW.CMS.Model.Organizations
{
    public class Organization : Party
    {
        public string Name { get; set; }

        public Organization()
        {
        }

    }//end Organization

}//end namespace Organizations